general.import = [
#"~/.config/alacritty/themes/tokyo-night.toml"
#"~/.config/alacritty/themes/solarized_light.toml"
#"~/.config/alacritty/themes/github_dark.toml"
#"~/.config/alacritty/themes/solarized_dark.toml"
"~/.config/alacritty/themes/nord.toml"
]
[env]
TERM = "xterm-256color"

[font]
size = 14
normal.family = "JetBrainsMono Nerd Font Mono"
#normal.family = "ComicShannsMono Nerd Font"


[window]
opacity = 0.95
#decorations="None"
#decorations="Transparent"
decorations="Buttonless"
dynamic_padding = true
blur=false

[window.padding]
x = 8 
y = 8 

[scrolling]
history = 2000

[keyboard]
bindings = [
{key = "N", mods = "Control|Shift", action = "CreateNewWindow"},
{key = "Enter", mods = "Command", action = "ToggleMaximized"},
{key = "Enter", mods = "Command|Shift", action = "ToggleFullScreen"},
{key = "T", mods = "Command", action = "None"},
]
